name: nationaldebtproblems
favicon: null
layout_spectrum: 0.2879619135055691
typography_spectrum: 0.68564886553213
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7512694133911282
  lightness: 0.08355159545317292
  saturation: 0.7700753207318485
  rhythmicContrast: 0.4266531001776457
purpose: []
